# Generated by Django 4.2.2 on 2024-12-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydetail',
            name='day_number',
            field=models.CharField(max_length=10),
        ),
    ]
