# Generated by Django 5.1.4 on 2025-01-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_rename_booking_date_booking_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
