# Generated by Django 5.1.4 on 2025-01-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_background_image_package_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
    ]
