# Generated by Django 4.2.2 on 2025-01-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_booking_first_name_booking_last_name_and_more'),
        ('package', '0003_delete_payment'),
    ]

    operations = [
    ]
