# Generated by Django 5.1.4 on 2025-01-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
