# Generated by Django 5.1.4 on 2025-01-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_package_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='min_members',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
