# Generated by Django 5.1.4 on 2025-01-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_remove_package_banner_image_packageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
