# Generated by Django 5.1.4 on 2025-01-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_package_min_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='payble_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
