# Generated by Django 4.2.2 on 2025-01-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_merge_20250108_1320'),
        ('package', '0005_alter_booking_contact_number_alter_booking_email'),
    ]

    operations = [
    ]
