# Generated by Django 5.1.4 on 2025-01-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_rename_total_price_booking_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payble_amount',
            new_name='payable_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
