# Generated by Django 5.1.4 on 2024-12-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_package_max_members_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payble_amount',
            new_name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
