# Generated by Django 5.1.4 on 2025-01-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_rename_payble_amount_booking_payable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pro_noun',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'mrs')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
