# Generated by Django 5.1.4 on 2024-12-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='advance_amount',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
