# Generated by Django 5.1.4 on 2024-12-19 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity')),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.CharField(choices=[('Hot', 'Hot'), ('Cool', 'Cool')], max_length=20)),
                ('staters', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('breakfast', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('lunch', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('dinner', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('desert', models.CharField(max_length=20)),
                ('juices', models.CharField(max_length=20)),
                ('cocktails', models.CharField(max_length=20)),
                ('shakes', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Food')),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_category', to='admins.foodcategory')),
            ],
        ),
    ]
