# Generated by Django 5.1.4 on 2024-12-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_activities_foodcategory_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='breakfast',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='cocktails',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='desert',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='dinner',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='drinks',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Cool', 'Cool')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='juices',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='lunch',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='shakes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='staters',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20, null=True),
        ),
    ]
