# Generated by Django 5.1.4 on 2024-12-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_item_category_remove_food_item_food_item_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='item_time',
            new_name='time',
        ),
    ]
