# Generated by Django 5.1.4 on 2024-12-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_rename_item_time_food_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_category',
            name='food_time',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Desert', 'Desert'), ('Dinner', 'Dinner')], max_length=250),
        ),
    ]
