# Generated by Django 5.1.4 on 2024-12-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_item_category_food_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_category',
            name='food_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=250),
        ),
    ]
