# Generated by Django 5.1.4 on 2024-12-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_rename_title_food_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Hot', 'Hot'), ('Cool', 'Cool')], max_length=20, null=True),
        ),
    ]
