# Generated by Django 5.1.4 on 2024-12-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_alter_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=250)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
