# Generated by Django 5.1.4 on 2024-12-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
