# Generated by Django 5.1.4 on 2024-12-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_alter_room_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
