# Generated by Django 5.1.4 on 2024-12-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_alter_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='food',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rating',
        ),
    ]
