# Generated by Django 4.2.2 on 2025-01-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_remove_activities_rating_remove_food_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
