# Generated by Django 4.2.2 on 2025-01-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
